#Importanto Bibliotecas

In [2]:
import numpy as np
import pandas as pd
from sklearn import cluster
import itertools
import matplotlib.pyplot as plt
import scipy.spatial
from sklearn import datasets
import sklearn

#Corringindo para ficar igual ao .dat

In [13]:
dados = pd.DataFrame(
    [[float(token) for token in line.split()]
        for line in open("luna_k5_f20_5000.dat") if line.strip()],
)

In [3]:
da = pd.read_csv('/content/drive/MyDrive/Faculdade./TCC./VDU./Aplicando CUDA no VDU./Algoritmo LUNA./Data/luna_k5_f20_5000.dat')

In [16]:
nome_arquivo = 'luna_k5_f20_5000.dat'

# Salvando o DataFrame em um arquivo de texto
da.to_csv(nome_arquivo, sep=' ', index=False)

In [12]:
# Caminho para o arquivo .dat original
caminho_arquivo_original = 'luna_k5_f20_5000t.dat'

# Caminho para o novo arquivo .dat sem a primeira linha
caminho_novo_arquivo = 'luna_k5_f20_5000.dat'

# Ler o conteúdo do arquivo original
with open(caminho_arquivo_original, 'r') as arquivo_original:
    linhas = arquivo_original.readlines()

# Remover a primeira linha
linhas = linhas[2:]

# Gravar o conteúdo restante no novo arquivo
with open(caminho_novo_arquivo, 'w') as novo_arquivo:
    novo_arquivo.writelines(linhas)

In [ ]:
dados.drop([0, 1], inplace=True)

In [14]:
df = dados

In [ ]:
target = []

for i in range(0, 5000000):
  if i >=0 and i<1000000:
    target.append(0)
  elif i>=1000000 and i<2000000:
    target.append(1)
  elif i>=2000000 and i<3000000:
    target.append(2)
  elif i>=3000000 and i<4000000:
    target.append(3)
  else:
    target.append(4)

In [ ]:
df = df.rename(index = lambda x: x -2)

In [15]:
df.head(5000000)

0         1         2         3         4         5         6   \
0     0.222535  0.200186  0.780563  0.714758  0.233531  0.194351  0.776167   
1     0.206185  0.187485  0.857306  0.695687  0.333872  0.240227  0.671780   
2     0.204085  0.251652  0.741292  0.717685  0.147784  0.262224  0.823108   
3     0.226953  0.311590  0.766620  0.741260  0.203177  0.260533  0.775739   
4     0.231541  0.237177  0.730875  0.801165  0.234644  0.285915  0.683551   
...        ...       ...       ...       ...       ...       ...       ...   
4995  0.682210  0.720518  0.711425  0.846827  0.177936  0.682285  0.242212   
4996  0.730033  0.788727  0.740299  0.821085  0.381495  0.749854  0.302880   
4997  0.819082  0.735794  0.844995  0.778933  0.313089  0.795886  0.174012   
4998  0.757459  0.700206  0.792109  0.747595  0.245076  0.767233  0.227255   
4999  0.804156  0.840968  0.740521  0.805204  0.215223  0.747478  0.299102   

            7         8         9         10        11        12        13  \
0     0.243835  0.301606  0.740356  0.722674  0.250327  0.735739  0.319103   
1     0.304926  0.104779  0.726580  0.693590  0.261526  0.737831  0.270593   
2     0.268659  0.255442  0.679781  0.757117  0.246481  0.713541  0.225670   
3     0.278017  0.306708  0.780848  0.738134  0.269277  0.761389  0.240341   
4     0.247409  0.254952  0.680880  0.683640  0.247512  0.747309  0.244248   
...        ...       ...       ...       ...       ...       ...       ...   
4995  0.307472  0.756541  0.753482  0.757640  0.173391  0.653161  0.723504   
4996  0.274651  0.687640  0.853151  0.840312  0.167374  0.820823  0.717489   
4997  0.327796  0.810871  0.752935  0.706119  0.272845  0.684247  0.772276   
4998  0.273018  0.774471  0.792393  0.729649  0.339807  0.736873  0.776376   
4999  0.207521  0.627786  0.729891  0.731042  0.208074  0.658111  0.798838   

            14        15        16        17        18        19  
0     0.289231  0.313123  0.319197  0.813667  0.186586  0.707657  
1     0.269523  0.296469  0.257454  0.783077  0.254783  0.706882  
2     0.211683  0.293236  0.291875  0.735521  0.254416  0.747027  
3     0.259431  0.237329  0.187099  0.749967  0.262177  0.740306  
4     0.320414  0.309259  0.219535  0.866130  0.197236  0.759473  
...        ...       ...       ...       ...       ...       ...  
4995  0.757128  0.325228  0.289671  0.723616  0.676543  0.286378  
4996  0.755447  0.259531  0.242154  0.758488  0.743667  0.180917  
4997  0.726528  0.297300  0.287963  0.779407  0.779865  0.220608  
4998  0.678308  0.231248  0.302580  0.677404  0.765564  0.247230  
4999  0.778235  0.351925  0.243885  0.663764  0.769887  0.203532  

[5000 rows x 20 columns]

#Manipulando


In [ ]:
n_clusters = 5
k_means = cluster.KMeans(n_clusters)
k_means.fit(df)

prediction = pd.concat([df, pd.DataFrame(target, columns=['pred'])], axis = 1)


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [ ]:
print(type(prediction))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
k_list = []
for i in range(n_clusters):
  clus = prediction.copy()
  clus = clus.loc[clus.pred == i]
  clus.drop(["pred"], axis=1, inplace=True)
  k_list.append(clus.values)

<ipython-input-39-34c20a21aded>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clus.drop(["pred"], axis=1, inplace=True)
<ipython-input-39-34c20a21aded>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clus.drop(["pred"], axis=1, inplace=True)
<ipython-input-39-34c20a21aded>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clus.drop(["pred"], axis=1, inplace=True)


In [ ]:
for i in range (0, len(k_list)):
  print(k_list[i])

[[0.6868597  0.7065989  0.26345885 ... 0.8047315  0.22905143 0.23268141]
 [0.7983059  0.68183094 0.15726784 ... 0.79380774 0.30333775 0.19132341]
 [0.7514211  0.7608816  0.2219166  ... 0.85490024 0.20728101 0.21822692]
 ...
 [0.72573286 0.73220646 0.27704293 ... 0.82862055 0.27152675 0.29727998]
 [0.6934136  0.68348724 0.29285342 ... 0.7715166  0.19232453 0.18950143]
 [0.79091614 0.7361403  0.2550367  ... 0.7708781  0.32303578 0.17653835]]
[[0.75828284 0.2844682  0.25378668 ... 0.7446603  0.7258053  0.7724871 ]
 [0.71056664 0.26892442 0.1577777  ... 0.73087436 0.9044732  0.75654083]
 [0.7185299  0.28691515 0.28341925 ... 0.79721045 0.7476191  0.73918605]
 ...
 [0.7607135  0.14741635 0.19362523 ... 0.78470075 0.778316   0.6642627 ]
 [0.7927674  0.25451586 0.18519948 ... 0.6840459  0.7397047  0.7158153 ]
 [0.8266277  0.22844508 0.22778441 ... 0.7230693  0.72597635 0.77940315]]
[[0.80723786 0.72650826 0.83717036 ... 0.24916153 0.14151989 0.33246985]
 [0.77386814 0.819483   0.7427365  ... 

#Calculando o centroid global

In [ ]:
ce_global = df.mean()

In [ ]:
ce_global = ce_global.to_numpy()

In [ ]:
print(ce_global)

[0.74997385 0.54997444 0.350012   0.65001825 0.45003178 0.54998819
 0.45000831 0.55002216 0.65000516 0.4499835  0.54997782 0.65000662
 0.44999131 0.45001688 0.6500174  0.44999259 0.65002162 0.45001169
 0.45002054 0.55001301]


#Minimo

In [ ]:
def δ(ck, ce_global):
    values = np.ones(len(ck))
    for i in range(0, len(ck)):
      ce = pd.DataFrame(ck[i])
      ce = ce.mean()
      ce = ce.to_numpy()
      values[i] = np.sqrt(np.sum(np.power(ce-ce_global, 2)))
    inter = np.min(values)
    return inter

In [ ]:
δ(k_list, ce_global)

0.8887683131113149

#Maximo

In [ ]:
def Δ(ci):
    values = np.zeros(len(ci))
    ce = pd.DataFrame(ci)
    ce = ce.mean()
    ce = ce.to_numpy()
    for i in range(0, len(ci)):
      values[i] = np.sqrt(np.sum(np.power(ce-ci[i], 2)))
    return np.max(values)

In [ ]:
Δ(k_list[1])

0.41127812581454576

Dunn

In [ ]:
def dunn(k_list, ce_global):
    δs = np.ones(len(k_list))
    Δs = np.zeros(len(k_list))
    d = []
    d2 = []
    δs = δ(k_list, ce_global)
    d.append(δs)
    for k in range(0, len(k_list)):
      Δs[k] = Δ(k_list[k])
      d2.append(Δs[k])
    di = np.min(d)/np.max(d2)
    return di

In [ ]:
%%time
dunn(k_list, ce_global)

CPU times: user 58.2 s, sys: 117 ms, total: 58.4 s
Wall time: 59 s


2.363941064274645